{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "workflow-controller.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ .Values.configurations.argo.progressDeadlineSeconds }}
  replicas: {{ .Values.configurations.argo.replicas }}
  revisionHistoryLimit: {{ .Values.configurations.argo.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: workflow-controller
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.configurations.argo.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.configurations.argo.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workflow-controller
    spec:
      containers:
      - args: [
          "--configmap",
          '- {{ template "workflow-controller.name" . }}',
          "--executor-image",
          "- {{ .Values.images.argoexec.repository }}:{{ .Values.images.argoexec.tag }}"
        ]
        command:
        - workflow-controller
        env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.images.workflowController.repository }}:{{ .Values.images.workflowController.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: {{ template "workflow-controller.name" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ template "agro.name" . }}
      serviceAccountName: {{ template "agro.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.configurations.argo.template.spec.terminationGracePeriodSeconds }}
{{- end }}
