{{- if .Values.rbac.create }}
apiVersion: v1
data:
  accesskey: bWluaW8=
  secretkey: bWluaW8xMjM=
kind: Secret
metadata:
  name: mlpipeline-minio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
