{{- if .Values.rbac.create }}
apiVersion: v1
data:
  accesskey: {{ .Values.credentials.accessKey | b64enc }}
kind: Secret
metadata:
  name: v3io-webapi-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
