{{- if .Values.rbac.create }}
apiVersion: v1
data:
  accesskey: {{ .Values.configurations.credentials.accessKey | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-webapi-secret
  namespace: {{ .Release.Namespace }}
  labels:
      app: {{ template "argo.name" . }}
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
type: Opaque
{{- end }}
