{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ template "scheduledworkflow.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "scheduledworkflow.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "scheduledworkflow.name" . }}
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "scheduledworkflow.name" . }}
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - image: {{ .Values.images.scheduledworkflow.repository }}:{{ .Values.images.scheduledworkflow.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: {{ template "scheduledworkflow.name" . }}
        namespace: {{ .Release.Namespace }}
      serviceAccountName: {{ template "scheduledworkflow.name" . }}
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
