{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "api-server.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - env:
        - name: OBJECTSTORECONFIG_ACCESSKEY
          value: "{{ .Values.configurations.credentials.accessKey }}"
        - name: OBJECTSTORECONFIG_SECRETACCESSKEY
          value: minio123
        - name: OBJECTSTORECONFIG_BUCKETNAME
          value: "{{ .Values.storage.s3.bucketName }}"
        - name: OBJECTSTORECONFIG_PORT
          value: "{{ .Values.configurations.ports.nginxPort }}"
        - name: OBJECTSTORECONFIG_HOST
          value: v3io-webapi
        - name: OBJECTSTORECONFIG_MULTIPART_DISABLE
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.images.apiServer.repository }}:{{ .Values.images.apiServer.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: {{ template "api-server.name" . }}
        ports:
        - containerPort: 8888
        - containerPort: 8887
      serviceAccountName: {{ template "apiserver.serviceAccountName" . }}
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
