{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "api-server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: grpc
    port: 8887
    protocol: TCP
    targetPort: 8887
  selector:
    app: ml-pipeline
{{- end }}
