{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
  namespace: {{ .Release.Namespace }}
  labels:
    app: ml-pipeline-persistenceagent
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline-persistenceagent
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: ml-pipeline-persistenceagent
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - image: {{ .Values.images.persistenceagent.repository }}:{{ .Values.images.persistenceagent.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: ml-pipeline-persistenceagent
        namespace: {{ .Release.Namespace }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccountName: ml-pipeline-persistenceagent
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
