{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "mysql-init-script.name" . }}
  labels:
    app: {{ template "mysql-init-script.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  enable-root-remote-access.sql: |
    -- Allow passwordless (insecure) access to root user from anywhere
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
{{- end }}
