{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "mysql-pipelines.name" . }}
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "pipelines.name" . }}
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "pipelines.name" . }}
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      volumes:
        - name: {{ template "mysql-init-script.name" . }}
          configMap:
            name: {{ template "mysql-init-script.name" . }}
        - name: mysql-config
          configMap:
            name: {{ template "mysql-pipelines.name" . }}
        # Add MySQL data mount (Fuse)
        - name: mysql-fuse
          flexVolume:
            driver: "v3io/fuse"
            options:
              container: {{ .Values.storage.metadata.containerName }}
              subPath: /mlpipeline/mysql-kf
              accessKey: {{ .Values.configurations.credentials.accessKey }}
      initContainers:
        - name: init-mysql
          image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          command:
            - /bin/bash
            - /etc/config/mysql/init-v3io-mysql.sh
          securityContext:
            runAsUser: 1001
          volumeMounts:
            - name: mysql-fuse
              mountPath: "/var/lib/mysql"
            - name: mysql-config
              mountPath: /etc/config/mysql
      containers:
        - name: {{ .Values.configurations.mysql.spec.template.spec.containers.name }}
          image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          command: ["/bin/bash", "/etc/config/mysql/v3io-mysql.sh"]
          ports:
            - name: {{ template "mysql-pipelines.name" . }}
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /etc/config/mysql/health_check.sh
            initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - /etc/config/mysql/health_check.sh
            initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.periodSeconds }}
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          volumeMounts:
            - name: mysql-fuse
              mountPath: "/var/lib/mysql"
            - name: mysql-config
              mountPath: /etc/config/mysql
            - name: {{ template "mysql-init-script.name" . }}
              mountPath: /etc/config/mysql/init-scripts
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
