{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql
  labels:
    app: mysql-kf
    chart: mysql-0.0.1
    release: mysql-kf
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app: mysql-kf
    chart: mysql-0.0.1
    release: mysql-kf
    heritage: {{ .Release.Service }}
{{- end }}
