apiVersion: v1
appVersion: ">=0.2.1"
description: Kubeflow pipelines service
name: pipelines
version: 0.0.1
home: https://github.com/kubeflow/pipelines
icon: https://github.com/kubeflow/marketing-materials/blob/master/logos/Raster/Kubeflow-Logo-RGB.png
sources:
  - https://www.kubeflow.org/
maintainers:
  - name: nirsagi
    email: nirs@iguazio.com
