{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "viewer-crd.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline-viewer-crd
  template:
    metadata:
      labels:
        app: ml-pipeline-viewer-crd
    spec:
      containers:
      - image: {{ .Values.images.viewerCrdController.repository }}:{{ .Values.images.viewerCrdController.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: {{ template "viewer-crd.name" . }}
        env:
        - name: MAX_NUM_VIEWERS
          value: "50"
      serviceAccountName: {{ template "viewercrd.serviceAccountName" . }}
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
