{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: proxy-agent
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: proxy-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: proxy-agent
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: proxy-agent
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        image: {{ .Values.images.inverseProxyAgent.repository }}:{{ .Values.images.inverseProxyAgent.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: proxy-agent
      serviceAccountName: proxy-agent-runner
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
