{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-agent-runner
  namespace: {{ .Release.Namespace }}
  labels:
    app: proxy-agent-runner
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
