{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ml-pipeline-ui
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline-ui
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: ml-pipeline-ui
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - env:
        - name: MINIO_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: MINIO_PORT
          value: "{{ .Values.configurations.ports.nginxPort }}"
        - name: MINIO_HOST
          value: v3io-webapi
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: HTTP_AUTHORIZATION_KEY
          value: X-v3io-session-key
        - name: HTTP_AUTHORIZATION_DEFAULT_VALUE
          value: "{{ .Values.configurations.credentials.accessKey }}"
        - name: MINIO_V3IO
          value: "1"
        image: {{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: ml-pipeline-ui
        ports:
        - containerPort: 3000
      serviceAccountName: ml-pipeline-ui
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
