{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-ui
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ml-pipeline-ui
  template:
    metadata:
      labels:
        app: ml-pipeline-ui
    spec:
      containers:
      - env:
        - name: MINIO_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: MINIO_PORT
          value: "{{ .Values.port.nginxPort }}"
        - name: MINIO_HOST
          value: v3io-webapi
        - name: MINIO_ACCESS_KEY
          value: {{ .AccessKey }}
        - name: HTTP_AUTHORIZATION_KEY
          value: X-v3io-session-key
        - name: HTTP_AUTHORIZATION_DEFAULT_VALUE
          value: {{ .AccessKey }}
        - name: MINIO_V3IO
          value: "1"
        image: {{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: ml-pipeline-ui
        ports:
        - containerPort: 3000
      serviceAccountName: ml-pipeline-ui
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
