{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "ui.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "ui.name" . }}
      chart: {{ template "pipelines.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "ui.name" . }}
        chart: {{ template "pipelines.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - env:
        - name: MINIO_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: MINIO_PORT
          value: "{{ .Values.configurations.ports.nginxPort }}"
        - name: MINIO_HOST
          value: v3io-webapi
        - name: MINIO_ACCESS_KEY
          value: "{{ .Values.configurations.credentials.accessKey }}"
        - name: HTTP_AUTHORIZATION_KEY
          value: X-v3io-session-key
        - name: HTTP_AUTHORIZATION_DEFAULT_VALUE
          value: "{{ .Values.configurations.credentials.accessKey }}"
        - name: MINIO_V3IO
          value: "1"
        image: {{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: {{ template "ui.name" . }}
        ports:
        - containerPort: 3000
      serviceAccountName: {{ template "ui.name" . }}
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- end }}
