{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ml-pipeline-ui
{{- end }}
