{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ml-pipeline-ui
{{- end }}
